### ISSUE TITLE
Style compliance

### ISSUE THREAD

**Issue by talmo** [talmolab/track-mjx#34]
Right now, the codebase is a mess of conventions and style everywhere depending on where we ported things from.

In #18 + #24 we started towards a clean-up by implementing CI with Black and pydocstyle linting.

This issue tracks the progress in achieving compliance with these and other practices.

# TODOs

- [ ] Document practices in a style guide doc.
    - Reference: [sleap-io contributing guide](https://github.com/talmolab/sleap-io/blob/53c1062175c1780cd6cad2de51c3f52c1b011c7e/CONTRIBUTING.md)
- [ ] Revise docstrings
    - We will use [Google-style docstrings](https://google.github.io/styleguide/pyguide.html).
    - One sentence describe abstractly about the function purpose, and document each input argument with its corresponding types and the content it carries. 
- [ ] Add basic typing.
    - No `typing.Union` and etc., use modern conventions (e.g., `str | int` instead of `typing.Union[str, int]`). See [this cheatsheet for reference](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html).
    - We won't add array shape typing for now, nor apply mypy static type enforcement. These are for _documentation_. This will pair nicely with creating data classes to organize structured data.
- [ ] Replace `os.path`, related `os` module I/O operations, and string manipulation for paths with [`pathlib`](https://docs.python.org/3/library/pathlib.html).
- [ ] Replace `black` with `ruff` as the execution backend for linting (still use `black` format linting)
- [ ] Simplified function arguments to be specific like [`compute_<>_reward(data, reference_clip, weight)` ](https://github.com/talmolab/track-mjx/blob/f91ee5d9e729f3b16a0a4d003c50c8f325f38fe4/track_mjx/environment/task/reward.py#L44-L47) in the 
- [ ] Data classes for complex data object. Look for [DMPOConfig](https://github.com/talmolab/vnl-ray/blob/71dfc1055ec51755d32445f8bdd4413750b346a9/vnl_ray/agents/agent_dmpo.py#L29-L48) data class in `vnl_ray`. For variables that being passing along together, packing them into the same `dataclass` is cleaner.
- [ ] No Magic Number
